velolog/myauth/urls.py
"""
Some docstring
"""
from django.urls import path
from .views import MyProfileView, LoginView, LogoutView, top_secret_info_view

app_name = "myauth"

urlpatterns = [
    path("secret/", top_secret_info_view, name="hidden"),
    path("my/", MyProfileView.as_view(), name="my"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

velolog/velolog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('veloride/', include("veloride.urls")),
    path('myauth/', include("myauth.urls")),
]

velolog/veloride/urls.py
"""
Some docstring
"""
from django.urls import path
from .views import (
    BikesListView,
    BikeDetailView,
    BikeUpdateView,
    BikeCreateView,
    BikeDeleteView,

    BikeRidesListView,
    BikeRideDetailView,
    BikeRideCreateView,
    BikeRideUpdateView,
    BikeRideDeleteView,
)

app_name = "veloride"

urlpatterns = [
    path("", BikesListView.as_view(), name="index"),
    path("<int:pk>/", BikeDetailView.as_view(), name="details"),
    path("create/", BikeCreateView.as_view(), name="create"),
    path("<int:pk>/update/", BikeUpdateView.as_view(), name="update"),
    path("<int:pk>/confirm-delete/", BikeDeleteView.as_view(), name="delete"),

    path("bikerides/", BikeRidesListView.as_view(), name="bikerides"),
    path("bikerides/<int:pk>", BikeRideDetailView.as_view(), name="bikeride"),
    path("bikerides/create/", BikeRideCreateView.as_view(), name="create-bikeride"),
    path("bikerides/<int:pk>/update/", BikeRideUpdateView.as_view(), name="update-bikeride"),
    path("bikerides/<int:pk>/confirm-delete/", BikeRideDeleteView.as_view(), name="delete-bikeride"),
]

velolog/veloride/forms.py
"""
Some docstring
"""
from django.forms import ModelForm
from django.forms import Widget
from .models import Bike, BikeRide


WIDGET_CLASS_FOR_TYPE = {"BooleanField": "checkbox", "TextField": "textarea", "DateField": "textarea",
                         "DateTimeField": "text", "CharField": "text"}
WIDGET_FORMAT_FOR_TYPE = {"DateField": "d.m.Y", "DateTimeField": "d.m.Y H:i:s", "TimeField": "H:i:s"}


class BikeCreateForm(ModelForm):
    """
    Some docstring
    """
    class Meta:
        """
        Some docstring
        """
        model = Bike
        fields = ("manufacturer", "model_name", "model_year",
                  "bike_class", "bike_type",
                  "description", "is_new", "old_odo", "bought_date",
                  "bought_in", "price", "discount", "archived")

    def __init__(self, *args, **kwargs):
        """
        Some docstring
        """
        super().__init__(*args, **kwargs)
        for field in self.fields.items():
            # print(name, field, field.widget)
            widget: Widget = field.widget

            if str(field.__class__).find("BooleanField") > 0:
                widget.attrs["class"] = "checkbox"
            else:
                widget.attrs["class"] = "form-control"


class BikeUpdateForm(ModelForm):
    """
    Some docstring
    """
    class Meta:
        """
        Some docstring
        """
        model = Bike
        fields = ("manufacturer", "model_name", "model_year",
                  "bike_class", "bike_type",
                  "description", "is_new", "old_odo", "bought_date",
                  "bought_in", "price", "discount", "archived")

    def __init__(self, *args, **kwargs):
        """
        Some docstring
        """
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            # print(name, field, field.widget)
            widget: Widget = field.widget

            if str(field.__class__).find("BooleanField") > 0:
                widget.attrs["class"] = "checkbox"
            else:
                widget.attrs["class"] = "form-control"


class BikeRideCreateForm(ModelForm):
    """
    Some docstring
    """
    class Meta:
        """
        Some docstring
        """
        model = BikeRide
        fields = ("name", "description", "route", "ride_bike", "ride_type",
                  "ride_planned", "ride_was_with_me",
                  "ride_start_dt", "ride_finish_dt", "ride_time_all_h", "ride_time_all_m", "ride_time_h", "ride_time_m",
                  "ride_relax", "ride_kkal",
                  "ride_dst", "ride_odo", "ride_avg_s", "ride_max_s", "ride_avg_c", "ride_max_c", "ride_total_asc",
                  "ride_total_desc",
                  "ride_avg_pwr", "ride_max_pwr", "ride_fun_scale", "ride_hard_scale", "ride_url", "ride_track_url")

    def __init__(self, *args, **kwargs):
        """
        Some docstring
        """
        super().__init__(*args, **kwargs)
        for field in self.fields.items():
            # print(name, field, field.widget)
            widget: Widget = field.widget

            if str(field.__class__).find("BooleanField") > 0:
                widget.attrs["class"] = "checkbox"
            else:
                widget.attrs["class"] = "form-control"


class BikeRideUpdateForm(ModelForm):
    """
    Some docstring
    """
    class Meta:
        """
        Some docstring
        """
        model = BikeRide
        fields = ("name", "description", "route", "ride_bike", "ride_type",
                  "ride_planned", "ride_was_with_me",
                  "ride_start_dt", "ride_finish_dt", "ride_time_all_h", "ride_time_all_m", "ride_time_h", "ride_time_m",
                  "ride_relax", "ride_kkal",
                  "ride_dst", "ride_odo", "ride_avg_s", "ride_max_s", "ride_avg_c", "ride_max_c", "ride_total_asc",
                  "ride_total_desc",
                  "ride_avg_pwr", "ride_max_pwr", "ride_fun_scale", "ride_hard_scale", "ride_url", "ride_track_url")

    def __init__(self, *args, **kwargs):
        """
        Some docstring
        """
        super().__init__(*args, **kwargs)
        for field in self.fields.items():
            # print(name, field, field.widget)
            widget: Widget = field.widget

            if str(field.__class__).find("BooleanField") > 0:
                widget.attrs["class"] = "checkbox"
            else:
                widget.attrs["class"] = "form-control"

velolog/veloride/views.py
"""
Some docstring
"""
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView
from django.http import HttpResponseRedirect
from .models import Bike, BikeRide
from .forms import (BikeCreateForm, BikeUpdateForm,
                    BikeRideCreateForm, BikeRideUpdateForm,
                    )


class BikesListView(ListView):
    """
    Some docstring
    """
    template_name = "veloride/index.html"
    context_object_name = "veloride"
    queryset = (
        Bike
        .objects
        .select_related("bike_class")
        .select_related("bike_type")
        .filter(archived=False)
        .order_by("pk")
        .all()
    )


class BikeDetailView(DetailView):
    """
    Some docstring
    """
    template_name = "veloride/details.html"
    context_object_name = "bike"
    queryset = (
        Bike
        .objects
        .select_related("bike_class")
        .select_related("bike_type")
        .filter(archived=False)
        .order_by("pk")
        .all()
    )


class BikeCreateView(CreateView):
    """
    Some docstring
    """
    model = Bike
    form_class = BikeCreateForm

    def get_success_url(self):
        """
        Some docstring
        """
        return reverse("veloride:index")


class BikeUpdateView(UpdateView):
    """
    Some docstring
    """
    model = Bike
    form_class = BikeUpdateForm
    template_name = 'veloride/bike_update_form.html'
    success_url = reverse_lazy("veloride:index")


class BikeDeleteView(DeleteView):
    """
    Some docstring
    """
    model = Bike
    success_url = reverse_lazy("veloride:index")
    context_object_name = "bike"

    def form_valid(self, form):
        """
        Some docstring
        """
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class BikeRidesListView(ListView):
    """
    Some docstring
    """
    template_name = "veloride/bikerides_list.html"
    context_object_name = "bikerides"

    queryset = (
        BikeRide
        .objects
        .select_related("ride_bike")
        .select_related("ride_type")
        .order_by("ride_date")
        .all()
    )


class BikeRideDetailView(DetailView):
    """
    Some docstring
    """
    template_name = "veloride/bikeride_details.html"
    context_object_name = "bikeride"
    # ride_id = str(BikeRide.pk)
    queryset = (
        BikeRide
        .objects
        .select_related("ride_bike")
        .select_related("ride_type")
    )


class BikeRideCreateView(CreateView):
    """
    Some docstring
    """
    model = BikeRide
    form_class = BikeRideCreateForm

    def get_success_url(self):
        """
        Some docstring
        """
        return reverse("veloride:bikerides")


class BikeRideUpdateView(UpdateView):
    """
    Some docstring
    """
    model = BikeRide
    form_class = BikeRideUpdateForm

    def get_success_url(self):
        """
        Some docstring
        """
        return reverse("veloride:bikerides")


class BikeRideDeleteView(DeleteView):
    """
    Some docstring
    """
    model = BikeRide
    success_url = reverse_lazy("veloride:bikerides")
    context_object_name = "bikeride"

    def form_valid(self, form):
        """
        Some docstring
        """
        success_url = self.get_success_url()
        self.object.delete()
        return HttpResponseRedirect(success_url)

velolog/veloride/templates/veloride/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
      {% block title %}

      {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>
     {% block body %}
        <h1>Hello, world!</h1>
     {% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>

  <div>

  </div>
  <footer>
    <p></p>
      <div>
          <h6><strong>ВелоДневник (Демо)</strong> - <em>Домашние задания по Django ORM</em></h6>
      </div>
  </footer>
</html>

velolog/veloride/templates/veloride/bike_confirm_delete.html
{% extends 'veloride/base.html' %}

{% block title %}
  Удаление велосипеда {{ bike }}
{% endblock %}

{% block body %}
  <h1>Удалить велосипед</h1>
  <form method="post">
    {% csrf_token %}
    <p>Вы действительно хотите удалить "{{ bike }}"?</p>
    {{ form }}
    <a
      class="btn btn-secondary"
      href="{% url 'veloride:details' bike.pk %}">
      Отмена
    </a>
    <button class="btn btn-warning" type="submit">
      Удалить
    </button>
  </form>
{% endblock %}

velolog/veloride/templates/veloride/bike_form.html
{% extends 'veloride/base.html' %}

{% block title %}
  Новый велосипед
{% endblock %}

{% block body %}
  <h1>Создание новой записи</h1>

  <form method="post">
    {% csrf_token %}
    {{ form.as_div }}
    <p></p>
     <table class="table table-light table-borderless">
        <tbody>
            <thead>
                <tr>
                    <th class="fa-align-left" scope="col">
                        <h6><b>Доступные действия:</b></h6>
                        <button class="btn btn-success" type="submit">Сохранить</button>
                        <a class="btn btn-outline-secondary" href="{% url 'veloride:index' %}">Отмена</a>
                    </th>
                </tr>
            </thead>
        </tbody>
    </table>
  </form>
{% endblock %}

velolog/veloride/templates/veloride/bike_update_form.html
{% extends 'veloride/base.html' %}

{% block title %}
  Правка велосипеда
{% endblock %}

{% block body %}
  <h1>Правка записи</h1>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p></p>
     <table class="table table-light table-borderless">
        <tbody>
            <thead>
                <tr>
                    <th class="fa-align-left" scope="col">
                        <h6><b>Доступные действия:</b></h6>
                        <button class="btn btn-success" type="submit" value="Confirm">Сохранить</button>
                        <a class="btn btn-outline-secondary" href="{{request.META.HTTP_REFERER}}">Отмена</a>
                    </th>
                </tr>
            </thead>
        </tbody>
    </table>
  </form>
{% endblock %}

velolog/veloride/templates/veloride/bikeride_confirm_delete.html
{% extends 'veloride/base.html' %}

{% block title %}
  Удаление велозаезда <strong>{{ bikeride.name }}</strong>
{% endblock %}

{% block body %}
  <h1>Удалить велозаезд</h1>
  <form method="post">
    {% csrf_token %}
    <p>Вы действительно хотите удалить "{{ bikeride.name }}"?</p>
    {{ form }}
    <a
      class="btn btn-secondary"
      href="{% url 'veloride:bikeride' bikeride.pk %}">
      Отмена
    </a>
    <button class="btn btn-warning" type="submit">
      Удалить
    </button>
  </form>
{% endblock %}

velolog/veloride/templates/veloride/bikeride_details.html
{% extends "veloride/base.html" %}

{% block title %}
    {{ bikeride.name }} подробно
{% endblock %}

{% block body %}
    <h1>{{ bikeride.ride_type }} <strong>"{{ bikeride }}"</strong></h1>
    <p></p>
    <table class="table table-light table-bordered table-striped table-sm">
        <tbody>
            <tr class="align-middle">
                <th width="400">
                            <table class="table table-light table-borderless">
                                <tbody>
                                    <tr>
                                        <th class="fa-align-left" scope="col">
                                            <h6><b>Доступные действия:</b></h6>
                                            <a class="btn btn-outline-secondary" href="{% url 'veloride:update-bikeride' bikeride.pk %}">Редактировать</a>
                                            <a class="btn btn-outline-secondary" href="{% url 'veloride:delete-bikeride' bikeride.pk %}">Удалить</a>
                                            <a class="btn btn-outline-secondary" href="{% url 'veloride:bikerides' %}">Назад к списку</a>
                                        </th>
                                    </tr>
                                </tbody>
                            </table>
                </th>
                <td>
                    <table class="table table-light table-bordered table-striped table-sm">
                        <tbody>
                            <tr><th width="250">Наименование</th><td>{{ bikeride.name|default_if_none:'-' }}</td></tr>
                            <tr><th width="250">Описание</th><td>{{ bikeride.description|default_if_none:'-' }}</td></tr>
                            <tr><th width="250">Маршрут</th><td>{{ bikeride.route|default_if_none:'-' }}</td></tr>
                        </tbody>
                    </table>

                    <table class="table table-light table-bordered table-striped table-sm">
                        <tbody>
                            <tr><th width="250">Велосипед</th><td>{{ bikeride.ride_bike|default_if_none:'-' }}</td>
                                <td width="160">{{ bikeride.ride_kkal|default_if_none:'-' }} кКал</td><th width="160">Старт</th>
                                <th width="160">Финиш</th>
                            </tr>
                            <tr><th>Тип заезда</th><td>{{ bikeride.ride_type|default_if_none:'-' }}</td>
                                <th>Дата</th><td>{{ bikeride.ride_start_dt|date:"d.m.Y"|default_if_none:'-' }}</td>
                                <td>{{ bikeride.ride_finish_dt|date:"d.m.Y"|default_if_none:'-' }}</td>
                            </tr>
                            <tr><th>Статус</th>
                                <td>
                                    {% if bikeride.ride_planned %}
                                        ЗАПЛАНИРОВАНО
                                    {% else %}
                                        -
                                    {% endif %}
                                </td>
                                <th>Время</th><td>{{ bikeride.ride_start_dt|date:"H:i"|default_if_none:'-' }}</td>
                                <td>{{ bikeride.ride_finish_dt|date:"H:i"|default_if_none:'-' }}</td>
                            </tr>
                            <tr><th>Участие</th>
                                <td>
                                    {% if bikeride.ride_planned %}
                                        УЧАСТВОВАЛ
                                    {% else %}
                                        -
                                    {% endif %}
                                </td>
                                <td>{{ bikeride.ride_relax|floatformat:2|default_if_none:'-' }} %</td><td>П У Л Ь С</td>
                                <td>{{ bikeride.ride_avg_pwr|default_if_none:'-' }}/{{ bikeride.ride_max_pwr|default_if_none:'-' }} Вт</td>
                            </tr>
                        </tbody>
                    </table>
                    <table class="table table-light table-bordered table-striped table-sm">
                        <tbody>
                            <tr><th width="300">Общее время</th><td>{{ bikeride.ride_time_all_h|default_if_none:'-' }}:{{ bikeride.ride_time_all_m|default_if_none:'-' }}</td>
                                <th width="300">Время в движении</th><td>{{ bikeride.ride_time_h|default_if_none:'-' }}:{{ bikeride.ride_time_m|default_if_none:'-' }}</td>
                            </tr>
                            <tr><th>Дистанция, км</th><td>{{ bikeride.ride_dst|floatformat:1|default_if_none:'-' }}</td>
                                <th>Одометр после, км</th><td>{{ bikeride.ride_odo|floatformat:1|default_if_none:'-' }}</td>
                            </tr>
                            <tr><th>Скорость средняя, км/ч</th><td>{{ bikeride.ride_avg_s|floatformat:1|default_if_none:'-' }}</td>
                                <th>Скорость макс., км/ч</th><td>{{ bikeride.ride_max_s|floatformat:1|default_if_none:'-' }}</td>
                            </tr>
                            <tr><th>Мощность средняя, Вт</th><td>{{ bikeride.ride_avg_pwr|default_if_none:'-' }}</td>
                                <th>Мощность макс., Вт</th><td>{{ bikeride.ride_max_pwr|default_if_none:'-' }}</td>
                            </tr>
                            <tr><th>Каденс средний, об/мин</th><td>{{ bikeride.ride_avg_c|default_if_none:'-' }}</td>
                                <th>Каденс макс., об/мин</th><td>{{ bikeride.ride_max_c|default_if_none:'-' }}</td>
                            </tr>
                            <tr><th>Набор высоты, м</th><td>{{ bikeride.ride_total_asc|default_if_none:'-' }}</td>
                                <th>Сброс высоты, м</th><td>{{ bikeride.ride_total_desc|default_if_none:'-' }}</td>
                            </tr>
                            <tr><th>Оценка заезда (фан-фактор), %</th><td>{{ bikeride.ride_fun_scale|default_if_none:'-' }} %</td>
                                <th>Оценка сложности, %</th><td>{{ bikeride.ride_hard_scale|default_if_none:'-' }} %</td>
                            </tr>
                            <tr><th>Ссылка на заезд</th><td>{% if bikeride.ride_url %} <a href=' {{ bikeride.ride_url }}'> Перейти </a>{% endif %}</td>
                                <th>Ссылка на трек</th><td>{% if bikeride.ride_track_url %} <a href=' {{ bikeride.ride_track_url }}'> Перейти </a>{% endif %}</td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>
{% endblock %}

velolog/veloride/templates/veloride/bikeride_form.html
{% extends 'veloride/base.html' %}

{% block title %}
  Новый велозаезд
{% endblock %}

{% block body %}
  <h1>Создание новой записи</h1>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p></p>
     <table class="table table-light table-borderless">
        <tbody>
            <thead>
                <tr>
                    <th class="fa-align-left" scope="col">
                        <h6><b>Доступные действия:</b></h6>
                        <button class="btn btn-success" type="submit">Сохранить</button>
                        <a class="btn btn-outline-secondary" href="{% url 'veloride:bikerides' %}">Отмена</a>
                    </th>
                </tr>
            </thead>
        </tbody>
    </table>
  </form>
{% endblock %}

velolog/veloride/templates/veloride/bikeride_update_form.html
{% extends 'veloride/base.html' %}

{% block title %}
  Правка велозаезда
{% endblock %}

{% block body %}
  <h1>Редактирование записи</h1>

  <form method="post">
    {% csrf_token %}
    {{ form.as_div }}
    <p></p>
     <table class="table table-light table-borderless">
        <tbody>
            <thead>
                <tr>
                    <th class="fa-align-left" scope="col">
                        <h6><b>Доступные действия:</b></h6>
                        <button class="btn btn-success" type="submit">Сохранить</button>
                        <a class="btn btn-outline-secondary" href="{{request.META.HTTP_REFERER}}">Отмена</a>
                    </th>
                </tr>
            </thead>
        </tbody>
    </table>
  </form>
{% endblock %}

velolog/veloride/templates/veloride/bikerides_list.html
{% extends 'veloride/base.html' %}

{% block title %}
  Список велозаездов
{% endblock %}

{% block body %}
  <h1>Cписок велозаездов</h1>
    <p></p>
        <table class="table table-light table-bordered table-striped">
        <tbody>
             <tr class="align-middle"><th width="400">
                 {% if image_url %}
                      <img alt="Фото" src={{ image_url }}>
                 {% endif %}
                 <table class="table table-light table-borderless">
        <tbody>
            <thead>
                <tr>
                    <th class="fa-align-left" scope="col">
                        <h6><b>Доступные действия:</b></h6>
                        <a class="btn btn-outline-secondary" href="{% url 'veloride:create-bikeride' %}">Добавить</a>
                        <a class="btn btn-outline-secondary" href="{% url 'veloride:index' %}">Назад к списку</a>
                    </th>
                </tr>
            </thead>
        </tbody>
    </table>
             </th>
            <td>
     <table class="table table-light table-bordered table-striped">
        <tbody>
            <tr><th>Дата</th><th>Тип</th><th>Название</th><th>Велосипед</th><th width="100">Дистанция, км</th><th width="100">V ср, км/ч</th><th width="100">Общее время</th><th width="100">Время в пути</th></tr>
            {% for oper in bikerides %}
                <tr><td>{{ oper.ride_start_dt|date:"d.m.Y H:i"|default_if_none:'-' }}</td>
                    <td>{{ oper.ride_type|default_if_none:'-' }}</td>
                    <td><a href="{% url 'veloride:bikeride' oper.pk %}">{{ oper.name|default_if_none:'-' }}</a></td>
                    <td>{{ oper.ride_bike|default_if_none:'-' }}</td>
                    <td>{{ oper.ride_dst|floatformat:1|default_if_none:'-' }}</td>
                    <td>{{ oper.ride_avg_s|floatformat:1|default_if_none:'-' }}</td>
                    <td>{{ oper.ride_time_all_h|default_if_none:'-' }}:{{ oper.ride_time_all_m|default_if_none:'-' }}</td>
                    <td>{{ oper.ride_time_h|default_if_none:'-' }}:{{ oper.ride_time_m|default_if_none:'-' }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
            </td>
             </tr>
        </tbody>
        </table>
{% endblock %}

velolog/veloride/templates/veloride/details.html
{% extends "veloride/base.html" %}

{% block title %}
    {{ bike.model_name }} подробно
{% endblock %}

{% block body %}
    <h1>Велосипед <strong>{{ bike }}</strong></h1>
    <p></p>
    <table class="table table-light table-bordered table-striped table-sm">
        <tbody>
            <tr class="align-middle"><th width="400">
                {% if bike.main_pict %}
                      <img alt="Фото" src={{ bike.main_pict.url }}>
                {% endif %}
                <table class="table table-light table-borderless">
                     <tbody>
                         <thead>
                            <tr>
                                 <th class="fa-align-left" scope="col">
                                      <h6><b>Доступные действия:</b></h6>
                                      <a class="btn btn-outline-secondary" href="{% url 'veloride:update' bike.pk %}">Правка</a>
                                      <a class="btn btn-outline-secondary" href="{% url 'veloride:delete' bike.pk %}">Удалить</a>
                                      <a class="btn btn-outline-secondary" href="{% url 'veloride:index' %}">Назад к списку</a>
                                 </th>
                            </tr>
                         </thead>
                    </tbody>
                </table>
            </th>
            <td>
                <h5><strong>Характеристики подробно:</strong></h5>
              <p></p>
              <table class="table table-light table-bordered table-striped table-sm">
                <thead>
                  <tr>
                    <th scope="col" width="300">Свойство</th>
                    <th scope="col">Значение</th>
                  </tr>
                </thead>
                <tbody>
                <tr><td>Класс</td><td>{{ bike.bike_class|default_if_none:'-' }}</td>
                <tr><td>Тип</td><td>{{ bike.bike_type|default_if_none:'-' }}</td>
                <tr><td>Год выпуска</td><td>{{ bike.model_year|default_if_none:'-' }}</td>
                <tr><td>Дата приобретения</td><td>{{ bike.bought_date|date:"d.m.Y"|default_if_none:'-' }}</td>
                <tr><td>Место приобретения</td><td>{{ bike.bought_in|default_if_none:'-' }}</td>
                <tr><td>Цена, руб.</td><td>{{ bike.price|floatformat:2|default_if_none:'-' }}</td>
                <tr><td>Скидка, %</td><td>{{ bike.discount|default_if_none:'-' }}</td>
                <tr><td>Цена без скидки, руб.</td><td>{{ bike.orig_price|floatformat:2|default_if_none:'-' }}</td>
                <tr><td>Приобретен новым</td>
                    <td>
                        {% if bike.is_new %}
                            Да
                        {% else %}
                            Нет
                        {% endif %}
                    </td>
                {% if not bike.is_new %}
                    <tr><td>С пробегом, км</td><td>{{ bike.old_odo|default_if_none:'-' }}</td>
                {% endif %}
                <tr><td>Описание</td><td>{{ bike.description|default_if_none:'-' }}</td>
                </tbody>
              </table>
            </td></tr>

        </tbody>
    </table>
{% endblock %}

velolog/veloride/templates/veloride/index.html
{% extends 'veloride/base.html' %}

{% block title %}
  Список велосипедов
{% endblock %}

{% block body %}
  <h1>Cписок велосипедов</h1>
     <table class="table table-light table-bordered table-striped">
        <tbody>
             <tr class="align-middle"><th width="400">
                 {% if image_url %}
                      <img alt="Фото" src={{ image_url }}>
                 {% endif %}
                 <table class="table table-light table-borderless">
        <tbody>
            <thead>
                <tr>
                    <th class="fa-align-left" scope="col">
                        <h6><b>Доступные действия:</b></h6>
                        <a class="btn btn-outline-secondary" href="{% url 'veloride:create' %}">Добавить</a>
                        <a class="btn btn-outline-secondary" href="{% url 'veloride:bikerides' %}">Заезды</a>
                    </th>
                </tr>
            </thead>
        </tbody>
    </table>
             </th>
            <td>
             <table class="table table-light table-bordered table-striped table-sm">
                <tbody>
                    <tr>
                        <tr><th>Наименование</th><th>Класс</th><th>Тип</th><</tr>
                         {% for oper in veloride %}
                           <tr><th><a href="{% url 'veloride:details' oper.pk %}">{{ oper|default_if_none:'-' }}</a></th>
                          <td>{{ oper.bike_class|default_if_none:'-' }}</td>
                          <td>{{ oper.bike_type|default_if_none:'-' }}</td>
                          </tr>
                    </tr>
            {% endfor %}
                </tbody>
             </table>
             </td>
             </tr>
        </tbody>
    </table>
{% endblock %}